language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pytest
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls 
script:
  - "nosetest --with-coverage --cover-package=api"
  - "coverage report"
  after_success:
  - coveralls